---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: azure-credentials
  namespace: azure-credentials
  labels:
    cluster.open-cluster-management.io/type: azr
    cluster.open-cluster-management.io/credentials: ""
stringData:
  # resource group created for the DNS to be used as base in the installation
  baseDomainResourceGroupName: openenv-jrh4l
  cloudName: AzurePublicCloud
  # ClientId + ClientSecret + TenantId + SubscriptionId in json format
  osServicePrincipal.json: '{"clientId":"client_id_here","clientSecret":"client_secret_here","tenantId":"tenant_id_here","subscriptionId":"subscription_id_here"}'
  # base DNS to be used as base in the installation
  baseDomain: jrh4l.azure.something.io
  # Your pull secret for pulling the images
  pullSecret: >
    {pull_secret_here}
  # Your Private Key for accessing the machines
  ssh-privatekey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
            private_key_here
    -----END OPENSSH PRIVATE KEY-----
  # Your Public Key for accessing the machines
  ssh-publickey: >
    ssh-rsa
    public_key_here
  httpProxy: ""
  httpsProxy: ""
  noProxy: ""
  additionalTrustBundle: ""
